CREATE TABLE Clients
(
  clientKey VARCHAR (36) PRIMARY KEY,
  clientId BIGINT AUTO_INCREMENT,
  clientName VARCHAR (100),
  email VARCHAR (250)
);

CREATE TABLE Positions
(
  positionId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR (50),
  location VARCHAR (50)
);
